using Parse.Abstractions.Management;

namespace Parse.Abstractions.Storage
{
    /// <summary>
    /// A unit that can generate a relative path to a persistent storage file.
    /// </summary>
    public interface ICacheLocationConfiguration
    {
        /// <summary>
        /// The corresponding relative path generated by this <see cref="ICacheLocationConfiguration"/>.
        /// </summary>
        string GetRelativeStorageFilePath(IParseCorePlugins plugins);
    }
}
